version: '2'
services:
  postgresql:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"
  coding-dojo-server:
    image: coding-dojo-server:latest
    ports:
      - 19999:9999
    networks:
      - coding-dojo-network
networks:
  coding-dojo-network:
    driver: bridge